CREATE TABLE comments (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    content VARCHAR(255) NOT NULL,
    dateCreation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL,
    isVisible BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE
);